# Generated by Django 3.2.5 on 2021-08-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy_ip', models.TextField()),
                ('port_no', models.TextField()),
                ('firmware', models.TextField()),
                ('tftp_server', models.TextField()),
            ],
        ),
    ]
