# Generated by Django 3.2.5 on 2021-08-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210804_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firmware_Records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switch_vendor', models.CharField(blank=True, max_length=64, null=True)),
                ('time', models.DateField()),
                ('old_firmware', models.CharField(blank=True, max_length=64, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=64, null=True)),
                ('new_firmware', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
    ]
