# Generated by Django 3.2.5 on 2021-08-04 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_firmware_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmware_records',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
