# Generated by Django 3.2.5 on 2021-08-04 16:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_firmware_records_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firmware_records',
            name='time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
