# Generated by Django 3.2.5 on 2021-08-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_firmware_records_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='firmware_records',
            name='serial_no',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='firmware_records',
            name='stack_no',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='manual',
            name='stack_no',
            field=models.TextField(default='1'),
        ),
    ]
