# Generated by Django 3.2.5 on 2021-08-07 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210807_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firmware_records',
            old_name='serial_no',
            new_name='serial',
        ),
    ]
